// Generated by CoffeeScript 1.8.0
(function() {
  if (!which('redis-server')) {
    $('apt-get update');
    $('apt-get install -y redis-server');
    $('apt-get clean');
    rm('-rf', ['/var/lib/apt/lists/*', '/tmp/*', '/var/tmp/*']);
  }

}).call(this);
