// Generated by CoffeeScript 1.8.0
(function() {
  var is_win;

  is_win = /^win/.test(process.platform);

  module.exports = {
    prompt: null,
    grammar: 'default.peg',
    entrypoint: is_win ? null : ['/bin/sh', '-c'],
    lang: 'js',
    api: [[null, 'jssh-api-jssh'], ['util', 'jssh-api-util'], ['conf', 'jssh-api-conf']],
    require: [['_', 'lodash']],
    verbose: false,
    debug: false,
    undef: false,
    history: 100
  };

}).call(this);
