// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    prompt: null,
    grammar: 'default.peg',
    entrypoint: '/bin/sh -c',
    lang: 'js',
    api: [[null, 'jssh-api-jssh'], ['util', 'jssh-api-util'], ['conf', 'jssh-api-conf']],
    require: [['_', 'lodash']],
    verbose: false,
    debug: false,
    undef: false,
    history: 100
  };

}).call(this);
