// Generated by CoffeeScript 1.8.0
(function() {
  $;
  $('ifconfig');

  $(function() {
    return ls();
  });

  $(1);

  $0('ls');

  $(0)('whoami');

  $([1, 2, 3, 4])('ls /etc');

  $1(function() {
    return cd('../test');
  });

  $.all('rm -rf *');

  $.all(function() {
    return rm('-rf', '/');
  });

  $;

}).call(this);
